name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker-compose -f infra/docker-compose.yml build
      # Add environment-specific deployment steps here (push to registry, etc.)


